export const bestSellers = [
  {
    id: 1,
    name: "Esther Howard",
    company: "Louis Vuitton",
    image: "/images/seller-avatar-1.png",
    sales: 1258,
    amount: 778.35,
  },
  {
    id: 2,
    name: "Wade Warren",
    company: "Binford Ltd.",
    image: "/images/seller-avatar-2.png",
    sales: 1028,
    amount: 576.28,
  },
  {
    id: 3,
    name: "Cameron Williamson",
    company: "MasterCard",
    image: "/images/seller-avatar-3.png",
    sales: 985,
    amount: 446.61,
  },
  {
    id: 4,
    name: "Jenny Wilson",
    company: "Pizza Hut",
    image: "/images/seller-avatar-4.png",
    sales: 875,
    amount: 406.27,
  },
  {
    id: 5,
    name: "Leslie Alexander",
    company: "Apple",
    image: "/images/seller-avatar-5.png",
    sales: 630,
    amount: 396.84,
  },
  {
    id: 6,
    name: "Kristin Watson",
    company: "Starbucks",
    image: "/images/seller-avatar-6.png",
    sales: 563,
    amount: 351.02,
  },
];
